### ISSUE TITLE
error with the latest version of Clappr

### ISSUE THREAD

**Issue by tarkanlar** [flavioribeiro/clappr-rtmp-plugin#23]
I got this error with the latest version of Clappr. Older version working properly
```[error][t] error on event o5:progress trigger - TypeError: this.el.getBytesLoaded is not a function
    at t.n.progress.value (http://localhost:3333/dist/clappr.min.js:3:15261)
    at h (http://localhost:3333/dist/clappr.min.js:5:28729)
    at t.n.trigger.value (http://localhost:3333/dist/clappr.min.js:5:28003)
    at Function.o.trigger (http://localhost:3333/dist/clappr.min.js:6:5518)
    at <anonymous>:1:38```

**Comment by towerz** [comment]
@tarkanlar What version of Clappr are you using this plugin with? The plugin hasn't been updated to use with Clappr 0.2.x yet, so I'd recommend to keep using 0.1.13 for now.

Just use http://cdn.clappr.io/0.1.13/clappr.min.js instead of `/latest` and set the `baseUrl` parameter to `http://cdn.clappr.io/0.1.13`.

**Comment by tarkanlar** [comment]
Yep, it works with Cappr 0.1.13  Thanks.

Any suggestions how we can update this plugin to work with Clappr 0.2.x?

**Comment by cherihung** [comment]
any idea on when RTMP plugin will work with the 0.2.x version?

**Comment by flavioribeiro** [comment]
@tarkanlar we now have an updated version of the plugin, feel free to point to `ttp://cdn.jsdelivr.net/clappr.rtmp/latest/rtmp.min.js` if you want to use the latest clappr

**Comment by kingctan** [comment]
we here also has the same error with latest versions.

**Comment by ocramot** [comment]
Same as https://github.com/flavioribeiro/clappr-rtmp-plugin/issues/53

The missing functions (getBytesLoaded and getBytesTotal) were added in 6 July: https://github.com/flavioribeiro/clappr-rtmp-plugin/commit/e4d053bd0f798a0eb05f232048e1e09889ae672d

However the url http://cdn.jsdelivr.net/clappr.rtmp/latest/rtmp.min.js is still pointing to an old version of the plugin. So either you have to build the plugin yourself, or wait for someone to build and update the latest version.
